name: Pull request
on:
  pull_request:
    branches:
      - master
      - ced/tuesday-night
jobs:
  preview:
    # Only run this job for events that originate on this repository.
    if: github.event.pull_request.head.repo.full_name == github.repository
    env:
      GOPATH: ${{ github.workspace }}/go
    name: Build and deploy preview
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
          extended: true

      - name: Check out branch
        uses: actions/checkout@v2

      - name: Build and deploy preview
        run: make ci-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
          ALGOLIA_APP_SEARCH_KEY: ${{ vars.ALGOLIA_APP_SEARCH_KEY }}
          DEPLOYMENT_ENVIRONMENT: ${{ vars.DEPLOYMENT_ENVIRONMENT }}
          PULUMI_STACK_NAME: ${{ vars.PULUMI_STACK_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_TEST_AWS_SECRET_ACCESS_KEY }}
