name: Push testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    # Only run this step on the upstream repo.
    if: github.repository == 'pulumi/pulumi-hugo'
    env:
      GOPATH: ${{ github.workspace }}/go
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
          extended: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::571684982431:role/ContinuousDelivery
          role-session-name: docs-deploy
          role-duration-seconds: 7200
          aws-region: us-west-2

      - name: Check out branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}

      - name: Build assets
        run: |
          make ensure build-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build site
        run: make ci-push
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
          CDN_PULUMI_URN: ${{ vars.CDN_PULUMI_URN }}
          PULUMI_STACK_NAME: ${{ vars.PULUMI_STACK_NAME}}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DEPLOYMENT_ENVIRONMENT: ${{ vars.DEPLOYMENT_ENVIRONMENT }}
          # AWS_ACCESS_KEY_ID: ${{ secrets.CI_TEST_AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_TEST_AWS_SECRET_ACCESS_KEY }}

  # notify:
  #   if: failure()
  #   name: Send slack notification
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Slack Notification
  #       uses: docker://sholung/action-slack-notify:v2.3.0
  #       env:
  #         SLACK_CHANNEL: docs-ops-test
  #         SLACK_COLOR: "#F54242"
  #         SLACK_MESSAGE: "build failure in pulumi-hugo repo :meow_sad:"
  #         SLACK_USERNAME: hugobot
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_ICON: https://www.pulumi.com/logos/brand/avatar-on-white.png
